# -*- coding: utf-8 -*-
#https://rstudio-pubs-static.s3.amazonaws.com/79360_850b2a69980c4488b1db95987a24867a.html
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from gensim import corpora, models
import gensim

tokenizer = RegexpTokenizer(r'\w+')

# create English stop words list
#en_stop = get_stop_words('en')
en_stop = stopwords.words('portuguese')

# Create p_stemmer of class PorterStemmer
p_stemmer = PorterStemmer()

# compile sample documents into a list
doc_set = [
    "local                                                                       ",
    "ambiente atendimento comida                                                 ",
    "ambiente local pizza                                                        ",
    "opção preço                                                                 ",
    "atendimento lugar pizza                                                     ",
    "ambiente atendimento local pizza preço                                      ",
    "ambiente pizza                                                              ",
    "ambiente                                                                    ",
    "ambiente local serviço                                                      ",
    "atendimento local lugar pizza                                               ",
    "ambiente atendimento pizza                                                  ",
    "ambiente lugar opção                                                        ",
    "ambiente qualidade serviço                                                  ",
    "ambiente atendimento pizza                                                  ",
    "local                                                                       ",
    "comida lugar                                                                ",
    "ambiente lugar pizza                                                        ",
    "local opção                                                                 ",
    "ambiente                                                                    ",
    "pizza                                                                       ",
    "ambiente opção                                                              ",
    "atendimento pizza                                                           ",
    "lugar serviço                                                               ",
    "ambiente                                                                    ",
    "atendimento lugar pizza                                                     ",
    "ambiente pizza                                                              ",
    "atendimento localização lugar                                               ",
    "local pizza qualidade                                                       ",
    "ambiente lugar pizza                                                        ",
    "ambiente atendimento                                                        ",
    "ambiente atendimento pizza                                                  ",
    "ambiente serviço                                                            ",
    "ambiente atendimento                                                        ",
    "ambiente atendimento pizza                                                  ",
    "ambiente comida preço                                                       ",
    "pizza                                                                       ",
    "pizza preço                                                                 ",
    "lugar pizza                                                                 ",
    "opção qualidade                                                             ",
    "pizza                                                                       ",
    "preço                                                                       ",
    "ambiente atendimento local                                                  ",
    "ambiente pizza                                                              ",
    "pizza                                                                       ",
    "atendimento comida local                                                    ",
    "ambiente atendimento pizza                                                  ",
    "ambiente opção pizza                                                        ",
    "atendimento lugar                                                           ",
    "ambiente pizza                                                              ",
    "ambiente                                                                    ",
    "ambiente pizza                                                              ",
    "ambiente atendimento lugar                                                  ",
    "atendimento pizza                                                           ",
    "ambiente                                                                    ",
    "ambiente atendimento lugar pizza                                            ",
    "atendimento pizza restaurante                                               ",
    "ambiente comida lugar                                                       ",
    "lugar pizza                                                                 ",
    "ambiente                                                                    ",
    "pizza                                                                       ",
    "pizza                                                                       ",
    "pizza pratos restaurante                                                    ",
    "pizza restaurante                                                           ",
    "atendimento pizza                                                           ",
    "ambiente atendimento pizza qualidade                                        ",
    "ambiente localização pizza                                                  ",
    "atendimento pizza                                                           ",
    "pizza                                                                       ",
    "ambiente pizza                                                              ",
    "ambiente pizza                                                              ",
    "atendimento pizza                                                           ",
    "ambiente atendimento lugar pizza                                            ",
    "local pizza                                                                 ",
    "ambiente                                                                    ",
    "serviço                                                                     ",
    "ambiente pizza                                                              ",
    "ambiente                                                                    ",
    "local pizza                                                                 ",
    "ambiente                                                                    ",
    "atendimento lugar pizza preço qualidade                                     ",
    "ambiente lugar pizza preço                                                  ",
    "serviço                                                                     ",
    "pizza                                                                       ",
    "atendimento localização                                                     ",
    "lugar pizza                                                                 ",
    "ambiente pizza                                                              ",
    "ambiente pizza serviço                                                      ",
    "pizza restaurante                                                           ",
    "atendimento pizza restaurante                                               ",
    "local qualidade serviço                                                     ",
    "lugar serviço                                                               ",
    "pizza                                                                       ",
    "atendimento                                                                 ",
    "pizza                                                                       ",
    "ambiente pizza                                                              ",
    "local pizza vista                                                           ",
    "ambiente atendimento lugar pizza                                            ",
    "ambiente pizza serviço                                                      ",
    "atendimento pizza qualidade                                                 ",
    "ambiente pizza                                                              ",
    "ambiente                                                                    ",
    "local pizza                                                                 ",
    "ambiente pizza serviço                                                      ",
    "lugar pizza serviço                                                         ",
    "local pizza serviço                                                         ",
    "ambiente pizza                                                              ",
    "ambiente local                                                              ",
    "pizza                                                                       ",
    "ambiente pizza                                                              ",
    "ambiente pizza                                                              ",
    "pizza                                                                       ",
    "atendimento pizza                                                           ",
    "ambiente atendimento pizza                                                  ",
    "ambiente atendimento lugar                                                  ",
    "ambiente                                                                    ",
    "atendimento pizza                                                           ",
    "local                                                                       ",
    "pizza                                                                       ",
    "lugar pizza                                                                 ",
    "atendimento local pizza                                                     ",
    "ambiente pizza restaurante                                                  ",
    "ambiente atendimento preço                                                  ",
    "comida local restaurante                                                    ",
    "ambiente pizza                                                              ",
    "ambiente                                                                    ",
    "ambiente pizza                                                              ",
    "atendimento comida qualidade                                                ",
    "ambiente atendimento pizza                                                  ",
    "pizza                                                                       ",
    "local pizza                                                                 ",
    "ambiente                                                                    ",
    "lugar                                                                       ",
    "atendimento                                                                 ",
    "local                                                                       ",
    "ambiente local                                                              ",
    "ambiente localização                                                        ",
    "ambiente opção pizza                                                        ",
    "lugar                                                                       ",
    "pizza                                                                       ",
    "ambiente atendimento pizza preço                                            ",
    "pizza serviço                                                               ",
    "comida pizza                                                                ",
    "atendimento local pizza                                                     ",
    "pizza                                                                       ",
    "atendimento local qualidade                                                 ",
    "lugar                                                                       ",
    "ambiente atendimento pizza                                                  ",
    "ambiente atendimento local                                                  ",
    "ambiente atendimento pizza                                                  ",
    "ambiente atendimento pizza                                                  ",
    "lugar pizza                                                                 ",
    "ambiente atendimento pizza                                                  ",
    "ambiente atendimento                                                        ",
    "pizza                                                                       ",
    "ambiente localização lugar                                                  ",
    "lugar                                                                       ",
    "ambiente pizza                                                              ",
    "atendimento local pizza                                                     ",
    "pizza                                                                       ",
    "ambiente lugar pizza                                                        ",
    "local pizza                                                                 ",
    "pizza                                                                       ",
    "ambiente pizza serviço                                                      ",
    "qualidade                                                                   ",
    "atendimento comida localização pizza                                        ",
    "pizza                                                                       ",
    "lugar                                                                       ",
    "pizza                                                                       ",
    "ambiente                                                                    ",
    "ambiente preço qualidade                                                    ",
    "ambiente local                                                              ",
    "lugar                                                                       ",
    "ambiente                                                                    ",
    "lugar pizza                                                                 ",
    "pizza                                                                       ",
    "ambiente atendimento pizza                                                  ",
    "ambiente pizza                                                              ",
    "ambiente atendimento pizza preço                                            ",
    "ambiente                                                                    ",
    "ambiente atendimento pizza                                                  ",
    "ambiente preço                                                              ",
    "ambiente pizza                                                              ",
    "atendimento pizza                                                           ",
    "ambiente pizza                                                              ",
    "lugar pizza preço                                                           ",
    "ambiente atendimento                                                        ",
    "ambiente pizza restaurante                                                  ",
    "comida lugar                                                                ",
    "local lugar pizza                                                           ",
    "ambiente comida                                                             ",
    "ambiente lugar                                                              ",
    "ambiente atendimento                                                        ",
    "ambiente atendimento pizza                                                  ",
    "ambiente restaurante                                                        ",
    "atendimento localização lugar                                               ",
    "lugar                                                                       ",
    "atendimento pizza                                                           ",
    "pizza                                                                       ",
    "atendimento comida local pizza                                              ",
    "restaurante                                                                 ",
    "ambiente local pizza                                                        ",
    "lugar                                                                       ",
    "atendimento qualidade                                                       ",
    "lugar                                                                       ",
    "ambiente atendimento pizza                                                  ",
    "ambiente atendimento pizza                                                  ",
    "atendimento pizza                                                           ",
    "ambiente atendimento comida                                                 ",
    "atendimento                                                                 ",
    "comida                                                                      ",
    "ambiente comida preço                                                       ",
    "ambiente                                                                    ",
    "ambiente atendimento                                                        ",
    "ambiente restaurante                                                        ",
    "restaurante                                                                 ",
    "atendimento comida lugar preço                                              ",
    "ambiente atendimento comida preço restaurante                               ",
    "ambiente comida                                                             ",
    "comida lugar                                                                ",
    "local                                                                       ",
    "ambiente atendimento                                                        ",
    "opção pratos                                                                ",
    "comida restaurante                                                          ",
    "comida restaurante serviço                                                  ",
    "comida lugar serviço                                                        ",
    "ambiente restaurante                                                        ",
    "lugar restaurante                                                           ",
    "pratos qualidade                                                            ",
    "restaurante                                                                 ",
    "pratos                                                                      ",
    "ambiente atendimento                                                        ",
    "restaurante                                                                 ",
    "comida restaurante                                                          ",
    "comida pratos preço qualidade                                               ",
    "atendimento comida lugar                                                    ",
    "lugar restaurante                                                           ",
    "restaurante                                                                 ",
    "atendimento                                                                 ",
    "comida preço restaurante                                                    ",
    "comida local                                                                ",
    "serviço                                                                     ",
    "ambiente                                                                    ",
    "atendimento comida local pratos preço                                       ",
    "ambiente restaurante                                                        ",
    "comida local                                                                ",
    "ambiente atendimento pratos restaurante                                     ",
    "atendimento comida                                                          ",
    "atendimento comida                                                          ",
    "lugar pratos                                                                ",
    "ambiente atendimento comida                                                 ",
    "ambiente                                                                    ",
    "preço qualidade                                                             ",
    "qualidade                                                                   ",
    "restaurante                                                                 ",
    "comida lugar serviço                                                        ",
    "ambiente comida lugar                                                       ",
    "ambiente comida pratos serviço                                              ",
    "ambiente comida restaurante                                                 ",
    "ambiente restaurante                                                        ",
    "ambiente comida localização                                                 ",
    "ambiente lugar                                                              ",
    "serviço                                                                     ",
    "serviço                                                                     ",
    "atendimento comida preço                                                    ",
    "restaurante                                                                 ",
    "atendimento comida                                                          ",
    "comida                                                                      ",
    "comida restaurante                                                          ",
    "atendimento                                                                 ",
    "restaurante                                                                 ",
    "comida                                                                      ",
    "local opção qualidade                                                       ",
    "ambiente comida                                                             ",
    "lugar serviço                                                               ",
    "ambiente atendimento                                                        ",
    "pratos                                                                      ",
    "ambiente pratos                                                             ",
    "lugar preço serviço                                                         ",
    "atendimento                                                                 ",
    "ambiente comida preço                                                       ",
    "ambiente restaurante                                                        ",
    "restaurante                                                                 ",
    "ambiente atendimento comida                                                 ",
    "lugar restaurante                                                           ",
    "lugar                                                                       ",
    "restaurante                                                                 ",
    "ambiente                                                                    ",
    "comida                                                                      ",
    "pratos                                                                      ",
    "ambiente comida                                                             ",
    "pratos preço restaurante                                                    ",
    "comida restaurante                                                          ",
    "comida                                                                      ",
    "ambiente                                                                    ",
    "pratos                                                                      ",
    "atendimento                                                                 ",
    "ambiente                                                                    ",
    "ambiente comida                                                             ",
    "local                                                                       ",
    "atendimento comida                                                          ",
    "ambiente preço serviço                                                      ",
    "restaurante                                                                 ",
    "atendimento                                                                 ",
    "comida restaurante                                                          ",
    "atendimento comida                                                          ",
    "restaurante                                                                 ",
    "ambiente comida                                                             ",
    "ambiente atendimento comida opção restaurante                               ",
    "ambiente atendimento                                                        ",
    "ambiente comida preço                                                       ",
    "pratos preço serviço                                                        ",
    "ambiente atendimento comida                                                 ",
    "serviço                                                                     ",
    "ambiente opção restaurante                                                  ",
    "comida restaurante                                                          ",
    "comida localização                                                          ",
    "comida preço restaurante                                                    ",
    "comida preço serviço                                                        ",
    "atendimento comida restaurante                                              ",
    "pratos                                                                      ",
    "ambiente atendimento comida serviço                                         ",
    "ambiente atendimento comida restaurante                                     ",
    "comida                                                                      ",
    "local serviço                                                               ",
    "ambiente preço                                                              ",
    "comida local                                                                ",
    "pratos                                                                      ",
    "pratos                                                                      ",
    "pratos restaurante                                                          ",
    "comida lugar                                                                ",
    "comida local restaurante                                                    ",
    "atendimento comida                                                          ",
    "comida restaurante                                                          ",
    "atendimento pratos qualidade                                                ",
    "ambiente comida pratos restaurante                                          ",
    "ambiente comida lugar                                                       ",
    "ambiente comida lugar preço restaurante serviço                             ",
    "comida pratos serviço                                                       ",
    "comida local preço restaurante                                              ",
    "comida                                                                      ",
    "restaurante                                                                 ",
    "ambiente atendimento comida restaurante                                     ",
    "ambiente comida pratos                                                      ",
    "ambiente atendimento                                                        ",
    "ambiente localização opção                                                  ",
    "ambiente atendimento comida localização                                     ",
    "atendimento                                                                 ",
    "comida lugar                                                                ",
    "ambiente comida local serviço                                               ",
    "ambiente atendimento lugar pratos preço                                     ",
    "comida                                                                      ",
    "atendimento restaurante                                                     ",
    "comida pratos serviço                                                       ",
    "qualidade                                                                   ",
    "local restaurante                                                           ",
    "restaurante                                                                 ",
    "atendimento restaurante                                                     ",
    "atendimento comida                                                          ",
    "ambiente atendimento                                                        ",
    "atendimento comida local                                                    ",
    "ambiente                                                                    ",
    "ambiente serviço                                                            ",
    "comida local pratos qualidade                                               ",
    "pratos qualidade restaurante serviço                                        ",
    "restaurante                                                                 ",
    "comida                                                                      ",
    "ambiente serviço                                                            ",
    "atendimento                                                                 ",
    "pratos                                                                      ",
    "pratos serviço                                                              ",
    "preço                                                                       ",
    "ambiente atendimento comida                                                 ",
    "atendimento comida lugar restaurante                                        ",
    "ambiente                                                                    ",
    "atendimento local                                                           ",
    "local preço                                                                 ",
    "lugar preço qualidade                                                       ",
    "atendimento pratos restaurante                                              ",
    "atendimento comida preço                                                    ",
    "atendimento                                                                 ",
    "pratos                                                                      ",
    "comida                                                                      ",
    "ambiente restaurante                                                        ",
    "atendimento comida                                                          ",
    "ambiente comida                                                             ",
    "comida                                                                      ",
    "ambiente                                                                    ",
    "ambiente comida                                                             ",
    "ambiente comida lugar serviço                                               ",
    "atendimento comida local localização                                        ",
    "local opção                                                                 ",
    "ambiente                                                                    ",
    "ambiente comida serviço                                                     ",
    "comida                                                                      ",
    "atendimento pratos restaurante                                              ",
    "localização quartos                                                         ",
    "localização                                                                 ",
    "atendimento lugar                                                           ",
    "lugar                                                                       ",
    "localização quarto                                                          ",
    "café de a manhã                                                             ",
    "local                                                                       ",
    "lugar                                                                       ",
    "atendimento                                                                 ",
    "café de a manhã preço qualidade                                             ",
    "quarto                                                                      ",
    "café de a manhã                                                             ",
    "café de a manhã                                                             ",
    "café de a manhã quarto                                                      ",
    "atendimento lugar opção                                                     ",
    "café de a manhã                                                             ",
    "quartos                                                                     ",
    "atendimento café de a manhã                                                 ",
    "lugar opção quarto                                                          ",
    "atendimento                                                                 ",
    "ambiente lugar quartos                                                      ",
    "café de a manhã quarto                                                      ",
    "café de a manhã quartos                                                     ",
    "ambiente café de a manhã quarto                                             ",
    "café de a manhã lugar                                                       ",
    "café de a manhã quarto                                                      ",
    "café de a manhã                                                             ",
    "atendimento localização quartos                                             ",
    "café de a manhã                                                             ",
    "localização lugar                                                           ",
    "localização lugar quarto                                                    ",
    "café de a manhã local                                                       ",
    "café de a manhã                                                             ",
    "café de a manhã quarto                                                      ",
    "atendimento café de a manhã local localização quarto serviço                ",
    "localização                                                                 ",
    "ambiente café de a manhã quartos                                            ",
    "café de a manhã lugar quarto                                                ",
    "café de a manhã quarto                                                      ",
    "serviço                                                                     ",
    "local lugar                                                                 ",
    "quarto                                                                      ",
    "café de a manhã hotel lugar                                                 ",
    "café de a manhã                                                             ",
    "atendimento                                                                 ",
    "lugar                                                                       ",
    "atendimento café de a manhã opção                                           ",
    "ambiente café de a manhã                                                    ",
    "atendimento café de a manhã                                                 ",
    "atendimento quartos                                                         ",
    "atendimento quarto                                                          ",
    "café de a manhã localização                                                 ",
    "localização lugar                                                           ",
    "café de a manhã lugar                                                       ",
    "quartos                                                                     ",
    "atendimento opção quarto quartos                                            ",
    "hotel quartos                                                               ",
    "localização opção                                                           ",
    "café de a manhã opção                                                       ",
    "ambiente                                                                    ",
    "atendimento localização                                                     ",
    "atendimento qualidade                                                       ",
    "café de a manhã hotel quarto                                                ",
    "atendimento quartos                                                         ",
    "localização                                                                 ",
    "café de a manhã quartos                                                     ",
    "café de a manhã                                                             ",
    "atendimento lugar quarto                                                    ",
    "restaurante                                                                 ",
    "ambiente quarto                                                             ",
    "café de a manhã quarto                                                      ",
    "café de a manhã lugar                                                       ",
    "café de a manhã                                                             ",
    "café de a manhã local serviço                                               ",
    "atendimento café de a manhã lugar quartos                                   ",
    "atendimento café de a manhã localização                                     ",
    "atendimento                                                                 ",
    "atendimento café de a manhã opção                                           ",
    "lugar                                                                       ",
    "café de a manhã lugar                                                       ",
    "café de a manhã                                                             ",
    "café de a manhã                                                             ",
    "atendimento café de a manhã quarto                                          ",
    "ambiente hotel                                                              ",
    "atendimento comida lugar preço                                              ",
    "café de a manhã hotel                                                       ",
    "lugar                                                                       ",
    "pratos quarto                                                               ",
    "atendimento comida                                                          ",
    "atendimento opção vista                                                     ",
    "atendimento lugar vista                                                     ",
    "restaurante                                                                 ",
    "atendimento vista                                                           ",
    "atendimento                                                                 ",
    "pratos                                                                      ",
    "lugar pratos                                                                ",
    "atendimento comida                                                          ",
    "atendimento comida pratos                                                   ",
    "atendimento local vista                                                     ",
    "pratos vista                                                                ",
    "vista                                                                       ",
    "ambiente                                                                    ",
    "atendimento comida vista                                                    ",
    "ambiente atendimento comida                                                 ",
    "vista                                                                       ",
    "atendimento comida local vista                                              ",
    "atendimento pizza                                                           ",
    "ambiente comida vista                                                       ",
    "hotel                                                                       ",
    "comida lugar                                                                ",
    "lugar vista                                                                 ",
    "ambiente atendimento restaurante vista                                      ",
    "atendimento comida vista                                                    ",
    "vista                                                                       ",
    "lugar vista                                                                 ",
    "lugar                                                                       ",
    "vista                                                                       ",
    "vista                                                                       ",
    "hotel local                                                                 ",
    "lugar restaurante vista                                                     ",
    "ambiente atendimento vista                                                  ",
    "ambiente lugar                                                              ",
    "preço qualidade vista                                                       ",
    "vista                                                                       ",
    "comida lugar vista                                                          ",
    "ambiente                                                                    ",
    "atendimento comida                                                          ",
    "ambiente comida pizza pratos vista                                          ",
    "ambiente comida lugar                                                       ",
    "pratos restaurante serviço vista                                            ",
    "vista                                                                       ",
    "comida lugar                                                                ",
    "preço vista                                                                 ",
    "pratos vista                                                                ",
    "ambiente atendimento pratos restaurante                                     ",
    "vista                                                                       ",
    "ambiente comida lugar                                                       ",
    "comida preço restaurante                                                    ",
    "atendimento vista                                                           ",
    "lugar restaurante vista                                                     ",
    "lugar vista                                                                 ",
    "ambiente comida vista                                                       ",
    "atendimento comida lugar                                                    ",
    "lugar vista                                                                 ",
    "café de a manhã lugar                                                       ",
    "ambiente                                                                    ",
    "ambiente comida                                                             ",
    "ambiente atendimento lugar                                                  ",
    "comida restaurante vista                                                    ",
    "vista                                                                       ",
    "vista                                                                       ",
    "lugar                                                                       ",
    "preço vista                                                                 ",
    "ambiente atendimento lugar vista                                            ",
    "preço restaurante                                                           ",
    "ambiente comida                                                             ",
    "ambiente vista                                                              ",
    "comida lugar vista                                                          ",
    "atendimento                                                                 ",
    "atendimento comida vista                                                    ",
    "comida lugar qualidade restaurante serviço vista                            ",
    "vista                                                                       ",
    "hotel vista                                                                 ",
    "vista                                                                       ",
    "ambiente preço                                                              ",
    "comida                                                                      ",
    "ambiente lugar pratos                                                       ",
    "atendimento vista                                                           ",
    "ambiente                                                                    ",
    "ambiente atendimento comida vista                                           ",
    "ambiente serviço vista                                                      ",
    "vista                                                                       ",
    "vista                                                                       ",
    "comida vista                                                                ",
    "lugar                                                                       ",
    "local preço qualidade                                                       ",
    "pratos vista                                                                ",
    "lugar                                                                       ",
    "hotel vista                                                                 ",
    "ambiente lugar vista                                                        ",
    "lugar vista                                                                 ",
    "atendimento preço restaurante                                               ",
    "atendimento local vista                                                     ",
    "ambiente restaurante                                                        ",
    "comida qualidade                                                            ",
    "restaurante vista                                                           ",
    "atendimento localização lugar vista                                         ",
    "atendimento passeio                                                         ",
    "comida restaurante vista                                                    ",
    "comida restaurante                                                          ",
    "lugar                                                                       ",
    "comida vista                                                                ",
    "hotel lugar                                                                 ",
    "comida lugar vista                                                          ",
    "lugar                                                                       ",
    "lugar vista                                                                 ",
    "comida vista                                                                ",
    "pratos restaurante vista                                                    ",
    "ambiente serviço vista                                                      ",
    "atendimento pratos vista                                                    ",
    "vista                                                                       ",
    "lugar                                                                       ",
    "ambiente lugar opção vista                                                  ",
    "ambiente atendimento comida                                                 ",
    "ambiente atendimento vista                                                  ",
    "local serviço                                                               ",
    "atendimento local vista                                                     ",
    "lugar                                                                       ",
    "atendimento vista                                                           ",
    "atendimento comida                                                          ",
    "ambiente                                                                    ",
    "lugar vista                                                                 ",
    "vista                                                                       ",
    "atendimento vista                                                           ",
    "restaurante                                                                 ",
    "atendimento lugar vista                                                     ",
    "atendimento                                                                 ",
    "atendimento local lugar                                                     ",
    "ambiente comida lugar                                                       ",
    "lugar                                                                       ",
    "comida                                                                      ",
    "ambiente hotel vista                                                        ",
    "pratos vista                                                                ",
    "atendimento                                                                 ",
    "lugar vista                                                                 ",
    "atendimento lugar                                                           ",
    "ambiente restaurante                                                        ",
    "lugar                                                                       ",
    "atendimento comida vista                                                    ",
    "comida local restaurante vista                                              ",
    "local serviço vista                                                         ",
    "lugar                                                                       ",
    "vista                                                                       ",
    "atendimento comida vista                                                    ",
    "comida opção restaurante vista                                              ",
    "local lugar                                                                 ",
    "vista                                                                       ",
    "lugar                                                                       ",
    "lugar pratos restaurante                                                    ",
    "vista                                                                       ",
    "vista                                                                       ",
    "atendimento opção                                                           ",
    "comida lugar                                                                ",
    "comida                                                                      ",
    "comida lugar vista                                                          ",
    "lugar vista                                                                 ",
    "pratos vista                                                                ",
    "comida                                                                      ",
    "lugar vista                                                                 ",
    "lugar pratos vista                                                          ",
    "ambiente comida lugar vista                                                 ",
    "local                                                                       ",
    "ambiente preço vista                                                        ",
    "lugar serviço                                                               ",
    "ambiente                                                                    ",
    "comida                                                                      ",
    "restaurante vista                                                           ",
    "local vista                                                                 ",
    "pratos                                                                      ",
    "preço restaurante                                                           ",
    "atendimento comida preço                                                    ",
    "lugar vista                                                                 ",
    "atendimento vista                                                           ",
    "comida opção restaurante                                                    ",
    "pizza vista                                                                 ",
    "vista                                                                       ",
    "comida vista                                                                ",
    "atendimento restaurante vista                                               ",
    "atendimento comida lugar vista                                              ",
    "ambiente comida                                                             ",
    "local vista                                                                 ",
    "comida preço                                                                ",
    "vista                                                                       ",
    "atendimento local preço vista                                               ",
    "atendimento lugar vista                                                     ",
    "atendimento comida local lugar vista                                        ",
    "atendimento vista                                                           ",
    "pizza                                                                       ",
    "ambiente comida pratos vista                                                ",
    "vista                                                                       ",
    "vista                                                                       ",
    "vista                                                                       ",
    "vista                                                                       ",
    "atendimento comida local vista                                              ",
    "ambiente comida                                                             ",
    "atendimento comida lugar vista                                              ",
    "ambiente atendimento pratos                                                 ",
    "ambiente atendimento lugar vista                                            ",
    "atendimento local lugar                                                     ",
    "ambiente atendimento vista                                                  ",
    "comida local                                                                ",
    "lugar                                                                       ",
    "vista                                                                       ",
    "local                                                                       ",
    "vista                                                                       ",
    "vista                                                                       ",
    "ambiente lugar                                                              ",
    "ambiente pratos                                                             ",
    "atendimento lugar qualidade                                                 ",
    "vista                                                                       ",
    "atendimento                                                                 ",
    "atendimento restaurante                                                     ",
    "ambiente comida vista                                                       ",
    "ambiente hotel lugar vista                                                  ",
    "ambiente atendimento comida vista                                           ",
    "atendimento qualidade restaurante vista                                     ",
    "vista                                                                       ",
    "comida vista                                                                ",
    "comida lugar serviço                                                        ",
    "lugar vista                                                                 ",
    "atendimento                                                                 ",
    "ambiente atendimento                                                        ",
    "atendimento local lugar vista                                               ",
    "vista                                                                       ",
    "ambiente vista                                                              ",
    "ambiente comida preço serviço                                               ",
    "atendimento hotel                                                           ",
    "atendimento pratos restaurante vista                                        ",
    "ambiente comida                                                             ",
    "atendimento comida vista                                                    ",
    "lugar pizza vista                                                           ",
    "lugar vista                                                                 ",
    "vista                                                                       ",
    "ambiente                                                                    ",
    "hotel local vista                                                           ",
    "lugar                                                                       ",
    "serviço vista                                                               ",
    "atendimento preço                                                           ",
    "pizza preço                                                                 ",
    "localização                                                                 ",
    "restaurante                                                                 ",
    "ambiente atendimento comida restaurante                                     ",
    "ambiente local passeio vista                                                ",
    "ambiente atendimento vista                                                  ",
    "vista                                                                       ",
    "ambiente comida                                                             ",
    "local qualidade vista                                                       ",
    "ambiente restaurante vista                                                  ",
    "vista                                                                       ",
    "lugar vista                                                                 ",
    "atendimento local                                                           ",
    "comida                                                                      ",
    "ambiente comida vista                                                       ",
    "vista                                                                       ",
    "atendimento preço qualidade restaurante vista                               ",
    "ambiente vista                                                              ",
    "comida lugar                                                                ",
    "atendimento vista                                                           ",
    "vista                                                                       ",
    "ambiente comida vista                                                       ",
    "lugar                                                                       ",
    "ambiente lugar                                                              ",
    "ambiente preço vista                                                        ",
    "comida pratos                                                               ",
    "ambiente atendimento lugar                                                  ",
    "pratos vista                                                                ",
    "ambiente vista                                                              ",
    "comida serviço vista                                                        ",
    "atendimento opção                                                           ",
    "ambiente comida                                                             ",
    "comida vista                                                                ",
    "vista                                                                       ",
    "ambiente serviço                                                            ",
    "ambiente                                                                    ",
    "vista                                                                       ",
    "comida lugar                                                                ",
    "ambiente atendimento vista                                                  ",
    "vista                                                                       ",
    "passeio restaurante                                                         ",
    "atendimento                                                                 ",
    "comida lugar vista                                                          ",
    "atendimento comida preço restaurante                                        ",
    "comida lugar restaurante                                                    ",
    "lugar                                                                       ",
    "qualidade serviço                                                           ",
    "restaurante                                                                 ",
    "atendimento lugar vista                                                     ",
    "atendimento vista                                                           ",
    "comida local                                                                ",
    "atendimento vista                                                           ",
    "atendimento lugar vista                                                     ",
    "vista                                                                       ",
    "vista                                                                       ",
    "atendimento comida vista                                                    ",
    "local lugar                                                                 ",
    "comida local                                                                ",
    "lugar pratos vista                                                          ",
    "opção                                                                       ",
    "vista                                                                       ",
    "ambiente comida                                                             ",
    "ambiente comida serviço vista                                               ",
    "atendimento comida restaurante vista                                        ",
    "vista                                                                       ",
    "ambiente qualidade vista                                                    ",
    "hotel                                                                       ",
    "local restaurante vista                                                     ",
    "comida lugar serviço vista                                                  ",
    "vista                                                                       ",
    "lugar vista                                                                 ",
    "ambiente comida                                                             ",
    "vista                                                                       ",
    "lugar vista                                                                 ",
    "ambiente serviço vista                                                      ",
    "atendimento restaurante                                                     ",
    "ambiente vista                                                              ",
    "atendimento vista                                                           ",
    "vista                                                                       ",
    "ambiente atendimento lugar pratos vista                                     ",
    "comida                                                                      ",
    "preço                                                                       ",
    "atendimento comida vista                                                    ",
    "lugar                                                                       ",
    "comida restaurante                                                          ",
    "comida lugar serviço vista                                                  ",
    "comida vista                                                                ",
    "comida lugar vista                                                          ",
    "comida serviço                                                              ",
    "vista                                                                       ",
    "pratos vista                                                                ",
    "atendimento comida lugar                                                    ",
    "ambiente comida vista                                                       ",
    "atendimento lugar                                                           ",
    "vista                                                                       ",
    "ambiente serviço                                                            ",
    "lugar                                                                       ",
    "atendimento lugar                                                           ",
    "atendimento comida vista                                                    ",
    "atendimento hotel localização vista                                         ",
    "ambiente                                                                    ",
    "atendimento hotel qualidade                                                 ",
    "qualidade                                                                   ",
    "ambiente restaurante vista                                                  ",
    "lugar                                                                       ",
    "opção restaurante vista                                                     ",
    "ambiente comida restaurante                                                 ",
    "atendimento comida local vista                                              ",
    "lugar                                                                       ",
    "ambiente comida pratos                                                      ",
    "atendimento pratos restaurante                                              ",
    "atendimento lugar vista                                                     ",
    "lugar vista                                                                 ",
    "ambiente pratos vista                                                       ",
    "lugar                                                                       ",
    "restaurante vista                                                           ",
    "local vista                                                                 ",
    "ambiente atendimento comida vista                                           ",
    "restaurante                                                                 ",
    "opção                                                                       ",
    "atendimento comida lugar                                                    ",
    "vista                                                                       ",
    "lugar                                                                       ",
    "comida vista                                                                ",
    "vista                                                                       ",
    "vista                                                                       ",
    "ambiente lugar vista                                                        ",
    "atendimento local lugar vista                                               ",
    "pratos serviço                                                              ",
    "atendimento comida vista                                                    ",
    "comida vista                                                                ",
]

#doc_set = [w.decode() for w in doc_set]

# list for tokenized documents in loop
texts = []

# loop through document list
for i in doc_set:

    # clean and tokenize document string
    raw = i.lower()
    tokens = tokenizer.tokenize(raw.decode('utf-8'))

    # remove stop words from tokens
    #stopped_tokens = [i for i in tokens if not i in en_stop]

    # stem tokens
    #stemmed_tokens = [p_stemmer.stem(i) for i in stopped_tokens]

    # add tokens to list
    texts.append(tokens)

# turn our tokenized documents into a id <-> term dictionary
dictionary = corpora.Dictionary(texts)
#print dictionary

# convert tokenized documents into a document-term matrix
corpus = [dictionary.doc2bow(text) for text in texts]
#print corpus

# generate LDA model
ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics=3, id2word = dictionary, passes=20)
print(ldamodel.print_topics(num_topics=3, num_words=4))